# Node.js
# Build a general Node.js project with npm.
# Add steps that analyze code, save build artifacts, deploy, and more:
# https://docs.microsoft.com/azure/devops/pipelines/languages/javascript

trigger:
- master

pool:
  vmImage: 'ubuntu-latest'

steps:
- task: NodeTool@0
  inputs:
    versionSpec: '12.x'
  displayName: 'Install Node.js'

- script: |
    npm run clean
  displayName: 'npm install and build'

- task: CopyFilesOverSSH@0
  inputs:
    sshEndpoint: 'Softimpression Server'
    contents: '**'
    targetFolder: '/Smartcodehub/Smartcodehub-api'
    readyTimeout: '20000'

- task: SSH@0
  inputs:
    sshEndpoint: 'Softimpression Server'
    runOptions: 'script'
    scriptPath: './dist/deploy.sh'
    readyTimeout: '20000'